apiVersion: v1
kind: Pod

metadata:
  name: configmap-test
  namespace: retailinventory

  labels:
    app.kubernetes.io/name: configmap-test
    app.kubernetes.io/component: playground
    app.kubernetes.io/instance: retailinventory
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: retailinventory-platform
    app.kubernetes.io/managed-by: kubectl

spec:

  containers:

    - name: alpine

      image: alpine:3.22

      command:
        - sh
        - -c
        - sleep 3600

      envFrom:

        - configMapRef:
            name: platform-config