apiVersion: v1
kind: Secret

metadata:
  name: sqlserver-secret
  namespace: retailinventory

  labels:
    app.kubernetes.io/name: sqlserver-secret
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: retailinventory
    app.kubernetes.io/version: "2022"
    app.kubernetes.io/part-of: retailinventory-platform
    app.kubernetes.io/managed-by: kubectl

type: Opaque

stringData:

  SA_PASSWORD: "RetailInv3ntory@2026"