name: CI - RetailInventory

on:
  push:
    branches:
      - "feature/message-broker-rabbitmq"

  pull_request:
    branches:
       - "feature/message-broker-rabbitmq"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "8.0.x"

      - name: Show .NET version
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore RetailInventory.Microservices/JMCloudLab.RetailInventoryPlatform.sln

      - name: Build solution
        run: dotnet build RetailInventory.Microservices/JMCloudLab.RetailInventoryPlatform.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test RetailInventory.Microservices/JMCloudLab.RetailInventoryPlatform.sln --configuration Release --no-build --no-restore --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: TestResults
          if-no-files-found: warn
          retention-days: 7
