apiVersion: v1
kind: ConfigMap

metadata:
  name: platform-config
  namespace: retailinventory

  labels:
    app.kubernetes.io/name: platform-config
    app.kubernetes.io/component: configuration
    app.kubernetes.io/instance: retailinventory
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: retailinventory-platform
    app.kubernetes.io/managed-by: kubectl

data:

  ASPNETCORE_ENVIRONMENT: "Development"

  TZ: "America/Lima"

  PLATFORM_NAME: "RetailInventory Platform"

  PLATFORM_VERSION: "1.0.0"