apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: rabbitmq-pvc
  namespace: retailinventory

  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/instance: retailinventory
    app.kubernetes.io/version: "3.13"
    app.kubernetes.io/part-of: retailinventory-platform
    app.kubernetes.io/managed-by: kubectl

spec:

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: standard