apiVersion: v1
kind: Secret

metadata:
  name: rabbitmq-secret
  namespace: retailinventory

  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/instance: retailinventory
    app.kubernetes.io/version: "3"
    app.kubernetes.io/part-of: retailinventory-platform
    app.kubernetes.io/managed-by: kubectl

type: Opaque

stringData:

  RABBITMQ_DEFAULT_USER: admin

  RABBITMQ_DEFAULT_PASS: Admin123*