apiVersion: v1
kind: Service

metadata:
  name: rabbitmq
  namespace: retailinventory

  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/instance: retailinventory
    app.kubernetes.io/version: "3.13"
    app.kubernetes.io/part-of: retailinventory-platform
    app.kubernetes.io/managed-by: kubectl

spec:

  type: ClusterIP

  selector:
    app.kubernetes.io/name: rabbitmq

  ports:

    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP

    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP