<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="RabbitMQ.Client" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\BuildingBlocks.Messaging\BuildingBlocks.Messaging.csproj" />
	  <ProjectReference Include="..\BuildingBlocks.Observability\BuildingBlocks.Observability.csproj" />
	</ItemGroup>
</Project>
