apiVersion: v1
kind: Namespace

metadata:
  name: retailinventory

  labels:
    app.kubernetes.io/name: retailinventory
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/instance: retailinventory
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: retailinventory-platform
    app.kubernetes.io/managed-by: kubectl

  annotations:
    description: "Retail Inventory Platform Namespace"